celika_dir = '../celika/'
celika_cflags = '-pedantic -Wall -std=c11 -g'
celika_ldflags = ''
celika_cflags_native = ''
celika_ldflags_native = ''
celika_cflags_emscripten = ''
celika_ldflags_emscripten = ''
celika_runopt = ''
celika_src = '$(wildcard *.c)'
celika_embedded_files = '$(wildcard *.c)'
celika_projname = 'snake'
