.PHONY: all
all: index.js

CELIKA_DIR = ../celika/
include $(CELIKA_DIR)Makefile

index.js: $(CELIKA_DEPS)
	@$(CC) snake.c $(CELIKA_LDFLAGS) $(CELIKA_CFLAGS) -o index.js \
	       --memory-init-file 0 -Oz

.PHONY: clean
clean:
	@rm -f index.js
