celika_dir = '../celika/'
celika_cflags = '-pedantic -Wall -std=c11'
celika_ldflags = ''
celika_cflags_native = '-g'
celika_ldflags_native = '-g'
celika_cflags_emscripten = '-Oz'
celika_ldflags_emscripten = '-Oz'
celika_runopt = ''
celika_src = 'main.c'
celika_embedded_files = 'OstrichSans-Medium.otf'
celika_projname = 'font-test' 
