.PHONY: all
all: index.js

CELIKA_DIR = ../celika/
include $(CELIKA_DIR)Makefile

index.js: $(CELIKA_DEPS)
	@$(CC) shooty_thing.c $(CELIKA_LDFLAGS) $(CELIKA_CFLAGS) -o index.js -Oz \
	       --embed-file SpaceShooterRedux/PNG/playerShip3_green.png \
	       --embed-file SpaceShooterRedux/PNG/ufoRed.png \
	       --embed-file SpaceShooterRedux/PNG/Lasers/laserGreen10.png \
	       --embed-file SpaceShooterRedux/PNG/Lasers/laserRed16.png \
	       --embed-file SpaceShooterRedux/PNG/Power-ups/pill_yellow.png \
	       --embed-file SpaceShooterRedux/PNG/Power-ups/bolt_gold.png \
	       --embed-file SpaceShooterRedux/Backgrounds/black.png \
	       --embed-file SpaceShooterRedux/Backgrounds/blue.png \
	       --embed-file SpaceShooterRedux/Backgrounds/darkPurple.png \
	       --embed-file SpaceShooterRedux/Backgrounds/purple.png \
	       --embed-file shaders/passthough.glsl \
	       --embed-file SpaceShooterRedux/Bonus/sfx_laser1.ogg \
	       --embed-file SpaceShooterRedux/Bonus/sfx_laser2.ogg \
	       --embed-file SpaceShooterRedux/Bonus/sfx_lose.ogg \
	       --memory-init-file 0

.PHONY: clean
clean:
	@rm -f index.js
